version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/Install_dependencies
      timeout: 300
    
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
   
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      
